### PR TITLE
Ql fixes

### PR DESCRIPTION
**Pull request by ankathur**
added modified console summary in quicklook_summary.txt

### CODE REVIEW

**Comment by ankathur** [comment]
@glassfishrobot  Run CI tests please

**Comment by ankathur** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — COMMENTED** [review]
Can you show how summary will look like wth these changes?

**Comment by ankathur** [comment]
quicklook_summary.txt is updated with this fix. It looks like this now 

    Test completed: Fri 05/26/2017 02:47:51 PDT 
    ===============================================
    QuickLookTests
    Total tests run: 115, Failures: 0, Skips: 0
    ===============================================
    ===============================================
    JaxwsFromWsdl Tests
    Total tests run: 2, Failures: 0, Skips: 0
    ===============================================
    ===============================================
     Jsr109tester Tests
    Total tests run: 2, Failures: 0, Skips: 0
    ===============================================

**Review by yaminikb — APPROVED** [review]

**Review by arindam-bandyopadhyay — APPROVED** [review]

**Pull request merged**
