### PR TITLE
Escape newline(ish) charaters for clean log in admin console

### PR DESCRIPTION
**Pull request by sameer-pandit**

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
