### PR TITLE
Repackaging and other cleanup

### PR DESCRIPTION
**Pull request by yaminikb**
-Changing from "packager" to "featureset" based distribution generation
-Removed unwanted installer related modules

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@yaminikb 

Can we also remove these?
- ant-tasks
- verifier
- appclient distribution

The packaging changes have an impact on the embedded distribution, you may want to do some extra testing on it.

**Comment by yaminikb** [comment]
@romain-grecourt I would rather incorporate your suggestions in the next phase and first get these changes in. Removing app client distribution is simple but I believe the removal of ant tasks or verifier will have a broader impact (tests, docs), hence I'm not comfortable removing them at this moment.

Regarding embedded distribution, I did perform manual checks on the generated jars by comparing with older jars. We also have embedded tests in our CI which helped validate the changes.

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by romain-grecourt** [comment]
@yaminikb ok no problem, lets get these changes in when the pipelines passes.

**Review by romain-grecourt — APPROVED** [review]

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
Just to add, CTS has passed with these changes.

**Pull request merged**
