### PR TITLE
Removed different versions for hibernate-validator in Glassfish.

### PR DESCRIPTION
**Pull request by sumauppa**
Removed different versions for hibernate-validator in Glassfish.
Removed tiger-types dependency from hk2-config.

### CODE REVIEW

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
It was failed due to copyright issue. Need to update them to 2018.

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
