### PR TITLE
Fix Issue 22483, Integrate Mojarra 2.4.0 to GlassFish

### PR DESCRIPTION
**Pull request by ruolli**

### CODE REVIEW

**Comment by ruolli** [comment]
@glassfishrobot Run CI tests please

**Comment by ruolli** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by ruolli** [comment]
Please hold the merge action. 
If possible, we would integrate a new version of Mojarra, rather than this 2.4.0 to GF.

**Comment by yaminikb** [comment]
OK.

-Yamini

**Pull request closed without merging**
