### PR TITLE
Solving jaxr-ra CTS issue

### PR DESCRIPTION
**Pull request by ankathur**
packaging jaxr-ra as rar and installing as application in glassfish

### CODE REVIEW

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Review by yaminikb — CHANGES_REQUESTED** [review]
The core changes seem fine but can you please fix the formatting in the new files?

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
