### PR TITLE
Fix #21963: Honour default-context-path of web.xml in case of an ear

### LINKED ISSUE #21963: Honour default-context-path in web.xml in case of an ear
Need to honour the default-context-path element specified in web.xml in case application.xml is not present in an EAR.

### PR DESCRIPTION
**Pull request by mskdeepak-oracle**
Fixes #21963

### CODE REVIEW

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — DISMISSED** [review]

**Review by vinayvishal — DISMISSED** [review]
We need to update the logic to determine context root based on presence/absence of default-context-path in the web.xml of an enterprise application.

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
