### PR TITLE
Update Jersey Version

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by lukasj** [comment]
@glassfishrobot run ci tests please

**Comment by jansupol** [comment]
4 tests failed. 
The first 2 do not use jersey: 
jsf-with-bundled-one-dot-one-jar-files
virtual-server-with-custom-error-report-valve

The later 2 have: java.lang.ClassNotFoundException: org.apache.jasper.runtime.JspRuntimeLibrary$PrivilegedIntrospectHelper not found by org.glassfish.web.javax.servlet.jsp [11]

[jsf_hello_world](http://sca00kou.us.oracle.com:8080/job/gf-remote-queue/1323/artifact/test-results/ql_gf_web_profile_all/results/QuickLookTests/jsf_hello_world.html)

**Comment by jansupol** [comment]
8 failures. The same as for Tyrus#22582.

**Comment by vinayvishal** [comment]
These failures are most likely due to some existing issue with CI pipeline. If changes are final, then we can go ahead and merge the PR. Can you please confirm?

**Review by vinayvishal — APPROVED** [review]
Looks good to me.

**Comment by jansupol** [comment]
Yes, the changes are final.

**Comment by jansupol** [comment]
@vinayvishal  For Eclipse GF, we would need to put new/Eclipse versions of the Jersey (2.28), Tyrus (1.15), JSON-P (1.1.3) there

**Comment by vinayvishal** [comment]
Are these Eclipse versions already released? If not, then I believe we need to have these integrated in Eclipse Glassfish first, once Eclipse versions are available, Eclipse Glassfish will then be updated again  with those versions.

**Comment by jansupol** [comment]
ok, will submit PRs

**Pull request merged**
