### PR TITLE
Fixes #21297. asadmin set command throws NPE on beans with readonly properties

### LINKED ISSUE #21297: asadmin set command throws NPE on beans with read only properties
When setting some configurable attribute via asadmin set command, the operation fails with "remote failure: Cannot change the element: null".
To reproduce, execute:
asadmin set configs.config.default-config.java-config.jvm-options=-server
#### Affected Versions
[4.1]

### PR DESCRIPTION
**Pull request by pranjal10**
Fixes #21297.

### CODE REVIEW

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by yaminikb** [comment]
Merged after verifying that all tests passed except a single copyright test failure unrelated to this change.

**Pull request merged**
