### PR TITLE
JAX-RS 2.1, Jersey 2.26.

### PR DESCRIPTION
**Pull request by pavelbucek**

### CODE REVIEW

**Comment by pavelbucek** [comment]
@glassfishrobot Run CI Tests please

**Comment by pavelbucek** [comment]
@glassfishrobot Run CI Tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI Tests please

**Comment by pavelbucek** [comment]
+ jaxrs cts run wa successful (see build 378)

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
