### PR TITLE
NoBug: Integrate latest JSR 375 API and RI (soteria) in glassfish 5.

### PR DESCRIPTION
**Pull request by sameer-pandit**
Integrate latest api and ri.
API update : javax.security.enterprise-api-1.0-b09.jar
RI update : javax.security.enterprise-1.0-b10.jar

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by arjantijms** [comment]
>as the html unit webclient is unable to send the cookie along with subsequent request after receiving it in 1st request.

Hmmmm, I can't remember having seen this before. The original test in Soteria seems to work just fine, or did you change something or add a new case?

**Comment by sameer-pandit** [comment]
Seems like I was using the old test code, fixed the el exp. and enabled the test.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by arjantijms** [comment]
>Seems like I was using the old test code, fixed the el exp. and enabled the test.

Ah, ok. That might explain it ;) Thanks for the update!

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]
Looks good

**Pull request merged**
