### PR TITLE
Reverting Metro and other components updates

### PR DESCRIPTION
**Pull request by yaminikb**
We need to revert the following updates that were part of c4163aa and 53b0139 since they are causing a regression:

metro
woodstox
stax2
saaj
mimepull
jaws
jaxb

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]
Looks Good

**Comment by arindam-bandyopadhyay** [comment]
Merging as there is copyright failure which is known failure

**Comment by arindam-bandyopadhyay** [comment]
This is revert commit for of PR #21970 and PR #21925

**Pull request merged**
