### PR TITLE
Tests cleanup - round 5

### PR DESCRIPTION
**Pull request by yaminikb**
-Updated many component versions used in test POMs (JUnit, Arquillian, HTMLUnit etc.)
-Updated many archives
-Added missing test sources
-Restored settings for security LDAP tests since previous commit caused a regression

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
Copyright job failed to trigger for unknown reason.

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by bshannon — DISMISSED** [review]
Approved once the backup filenames are fixed, as discussed in email.

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]
looks good

**Pull request merged**
