### PR TITLE
Fix #21138-After editing Availability service in configurations…

### LINKED ISSUE #21138: After editing Availability service in configurations domain.xml corrupted
1) Create some configuration
2) Edit Availability Service (anything ... f.e. turn SSO failover on)
3) Save

domain.xml then contains two elements
<availability-service></availability-service>

*   one is empty and one contains saved settings.

The result of this is that GUI does not reflect saved configuration and I could not start IMQ broker on cluster instances - the imq folder was not created and startup ended up with nullpointers in server.log!

Same problem is both using GUI and asadmin command. When I delete the empty element, everything works.
#### Affected Versions
[4.1_dev]

### PR DESCRIPTION
**Pull request by srinivaskrishnan**
… domain.xml corrupted

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
Please do not use old issue name as GLASSFISH-21138 . 
Please mention in the Pull Request description Fixes #21753 in order to link the issue with this pull request

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
Please mention in the comment that it fixes Fix #21138

**Comment by srinivaskrishnan** [comment]
This issue fixes #21138.

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
