### PR TITLE
Escape newline (ish) characters and encode html entities while logging

### PR DESCRIPTION
**Pull request by sameer-pandit**
Escape newline(ish) characters like CL RF ... etc for clean logging. Also encode chars for html e.g. < to &lt.
Add utils for safe header values.

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
