### PR TITLE
Add tests for issue #21496 : Validate for special encoded characters in request path

### LINKED ISSUE #21496: Directory traversal exposes file system resources
This vulnerability has been tested on windows and linux, GlassFish version 4.1, but is most likely in previous versions as well.

Assuming the GlassFish 4.1 admin console is running locally on 4848 use the following URL to display the asenv.conf file in a browser (no logon required):

[http://localhost:4848/theme/META-INF/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/config/asenv.conf](http://localhost:4848/theme/META-INF/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/config/asenv.conf)

A similar URL can be crafted to examine file system resources or web application resources. I have examples of URLs that can display the WEB-INF/web.xml or even the /etc/passwd file on a unix server.

Note that I have added this as a "critical" priority due to the nature of the potential security threat. Application level servlet filtering can be used to remove the threat but the only option with the admin console is to block the port via a firewall. Please contact me for more information if required.
#### Environment
Tested on both windows and linux
#### Affected Versions
[4.1]

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Fixes #21496 : The suggested fix validates special encoded characters in request path which exposes filesystem resources.

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by edburns — COMMENTED** [review]
Caveat: I am not familiar with this code, but I am offering my review because it was requested and because I feel capable of reviewing it based on my general proficiency.

StandardContextValve.java

lines 292 and 293: Can you verify that the code guards against the %nn escaping of "/" and "\".  For example, I'd be concerned with strings that contain some combination of those before and after the "..".  

I'll defer to Shing-wai to give the final approval.

**Comment by shingwaichan** [comment]
The issue description was about org.glassfish.grizzly.http.util.UTF8Decoder. It is would be good to ask Ryan to review this, too.

**Review by shingwaichan — CHANGES_REQUESTED** [review]
The current patch does now allow .. and : in url. This is more restrictive than disallowing illegal utf-8 character.

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
Between line 176-183 of WebTest.java, there are two 'break' inside the if/else. For this particular logic, we do not need a while loop and break here. Just read the line once.

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by shingwaichan — APPROVED** [review]

**Pull request merged**
