### PR TITLE
RQ infrastructure work

### PR DESCRIPTION
**Pull request by arindam-bandyopadhyay**
Improve the RQ command line client .

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
Run hudson tests please

**Review by romain-grecourt — APPROVED** [review]
I hereby approve this change :D

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run hudson tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run hudson tests please

**Pull request merged**
