### PR TITLE
Fixes #21907 : Added JDBC TestSuite to pipeline

### LINKED ISSUE #21907: Add JDBC testsuite
Jdbc testsuite needs to be added to the pipeline

### PR DESCRIPTION
**Pull request by YRutuja**
Fixes #21907: Added JDBC TestSuite to pipeline

### CODE REVIEW

**Comment by YRutuja** [comment]
@glassfishrobot Run CI tests please

**Review by arindam-bandyopadhyay — DISMISSED** [review]
Please change the copyright of newly added files.

**Comment by YRutuja** [comment]
@glassfishrobot Run CI tests please

**Comment by YRutuja** [comment]
@glassfishrobot Run CI tests please

**Comment by YRutuja** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
