### PR TITLE
java:app & java:module namespaces temporarily disappear when SAM invoked

### LINKED ISSUE #21447: java:app & java:module namespaces temporarily disappear when SAM invoked
When trying to obtain something from the JNDI namespace <tt>java:app</tt> or <tt>java:module</tt> during invocation of a SAM's <tt>validateRequest</tt> method an exception is thrown.

However, right before the SAM is invoked, namely in a <tt>ServletRequestListener</tt> as well as right after the SAM is invoked, namely in a Filter or Servlet this operation succeeds.

The exception thrown is the following:

```
javax.naming.NamingException: Lookup failed for 'java:module/EJBBean' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NamingException: Invocation exception: Got null ComponentInvocation ]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:491)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:438)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at test.TestServerAuthModule.validateRequest(TestServerAuthModule.java:40)
	at javax.security.authenticationmechanism.DefaultServerAuthContext.validateRequest(DefaultServerAuthContext.java:36)
	at com.sun.web.security.RealmAdapter.validate(RealmAdapter.java:1654)
	at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:1521)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:606)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:702)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:678)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.naming.NamingException: Invocation exception: Got null ComponentInvocation 
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.getComponentId(GlassfishNamingManagerImpl.java:842)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:714)
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:167)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:471)
```

The lookup code is as follows:

```
try {
	// java:global/glassfish-sam-ee-namespaces/EJBBean does work 	EJBBean ejbBean = (EJBBean) new InitialContext().lookup("java:module/EJBBean");
	System.out.println("SAM: " + ejbBean.hello());
} catch (NamingException e) {
	System.out.println("SAM: Exception");
	e.printStackTrace();
}
```

A full reproducer is provided as Maven project at: [https://github.com/arjantijms/glassfish-sam-ee-namespaces](https://github.com/arjantijms/glassfish-sam-ee-namespaces)

Building and deploying this project to a stock GlassFish, then requesting [http://localhost:8080/glassfish-sam-ee-namespaces/servlet](http://localhost:8080/glassfish-sam-ee-namespaces/servlet) prints the following in the log:

```
RequestListener: Hello from EJB
SAM: Exception
javax.naming.NamingException: Lookup failed for 'java:module/EJBBean' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} (rest of exception as above)
Servlet: Hello from EJB
```

Expected is:

```
RequestListener: Hello from EJB
SAM: Hello from EJB
Servlet: Hello from EJB
```

Deploying the same application to JBoss WildFly 9.0.1 or 10.0rc3 (with a modified standalone.xml to activate jaspic) indeed prints the above.
#### Affected Versions
[4.1.1, 5.0]

### PR DESCRIPTION
**Pull request by sameer-pandit**
Fixes #21447

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run Hudson Tests Please

**Review by yaminikb — COMMENTED** [review]
Changes look fine but it would be good to add a test case as well.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run Hudson Tests Please

**Comment by sameer-pandit** [comment]
@glassfishrobot  Run Hudson Tests Please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests Please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests Please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
