### PR TITLE
remove packager jmxremote_optional dependency

### PR DESCRIPTION
**Pull request by sameer-pandit**
removed packager jmxremote_optional

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Comment by sameer-pandit** [comment]
Following the config instructions [here](https://nabsha.wordpress.com/2014/04/09/enabling-jmxmp-connector-in-glassfish-v4-0/), I can still see the monitoring data on jconsole over jmxmp.
s1

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
