### PR TITLE
Split servlet tck tests to reduce overall runtime

### PR DESCRIPTION
**Pull request by debayan-gupta**

### CODE REVIEW

**Comment by debayan-gupta** [comment]
@glassfishrobot Run CI tests please

**Comment by debayan-gupta** [comment]
@glassfishrobot Run CI tests please

**Review by jsyxin — APPROVED** [review]
I just added tests for Servlet 4.0. Actually I am not familiar with test infra. From test case perspective, since the test cases in different directories are independent of each other. So I think it is fine for me.

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Pull request closed without merging**
