### PR TITLE
Moving connector to the appserver/tests/appserv-tests/devtests folder.

### LINKED ISSUE #21906: Enabling Connector Tests as Part of RQ...
Enable connector devtests as part of the RQ. 

## Environment Details
* GlassFish Version (and build number): 5.0-b08
* JDK version: 1.8.0_65
* OS: All

----------

## Problem Description
Enable connector devtests as part of the RQ. Provide new RQ target (connector_all) to run available connector tests.

## Steps to reproduce
It's just an enabling the connector test as part of RQ job.

### PR DESCRIPTION
**Pull request by naman223**
Fix #21906 
Moving tests to the proper folder.

### CODE REVIEW

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Review by arindam-bandyopadhyay — CHANGES_REQUESTED** [review]
Please delete connector test from apserver/tests/v2-tests as you have moved them under apserver/tests/appserv-tests/devtests

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
http://sca00kou.us.oracle.com:8080/job/gf-remote-queue/288/

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@naman223 
1. The tests suite is taking long time to run(1 hour 41 miniutes). Can we split the tests id such that it takes less time. e.g there would be connector_all terget along with that please define connector_group1 connector_group2 targets which are short running target. Please refer https://github.com/javaee/glassfish/blob/master/appserver/tests/appserv-tests/devtests/admin/cli/run_test.sh
2. Do we need all the directory under appserver/tests/appserv-tests/devtests/connector. I saw that the run_test.sh is under v3. Can we get rid of some directory under v3 if we are not using them in tests

**Comment by naman223** [comment]
We can't split test. These is old structure so I am not sure, is it feasible to move the test from v3 to parent folder. Might some directories are conflict also. It's better to keep the same as of now and merge. We can raise one more task to fix the same.

**Comment by arindam-bandyopadhyay** [comment]
Sure. Let's merge it now and once the tests ids are split we can add them in the pipeline.

**Review by arindam-bandyopadhyay — APPROVED** [review]

**Pull request merged**
