### PR TITLE
Removing redundant labels from Admin Console 

### PR DESCRIPTION
**Pull request by kokil12**
All the redundant labels have been removed from admingui code as it was causing multiple label error.
Test : Ran the admingui devtests successfully.

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please.

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please.

**Comment by yaminikb** [comment]
@kokil12 Have you run GUI dev tests?

**Review by yaminikb — APPROVED** [review]
Seems fine

**Comment by kokil12** [comment]
Yes. I ran the gui devtests successfully.

**Pull request merged**
