### PR TITLE
Cleaning up the repository

### PR DESCRIPTION
**Pull request by yaminikb**
-Removed many unwanted files
-Removed unsupported appclient distribution

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
This PR also includes changes for #22490

**Review by arindam-bandyopadhyay — APPROVED** [review]
Looks good

**Pull request merged**
