### PR TITLE
Add devtest using new schemas

### PR DESCRIPTION
**Pull request by mskdeepak-oracle**
Adding a devtest to test that deployment goes through with two new schemas - `application_8.xsd` and `application-client_8.xsd`

### CODE REVIEW

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
