### PR TITLE
Restructure GlassFish source code

### LINKED ISSUE #21822: Restructure GlassFish source code
I am planing to make the following changes in GlassFish source code structure to cleanup the repository.

1.**Delete 'V2' directory** - In time of GitHub migration, we have refactored the old trunk/v2/appserv-tests and put all active/valid tests under main/appserver/tests/appserv-tests/devtests in the GlassFish repository. Under v2/appserv-tests, we kept only those tests that haven't been refactored(mostly they are legacy and not running in CI). Instead of putting v2/ as a top level directory,we would be moving it under appserver/tests/v2-tests.
2.**Delete copyright module** - copyright module is there in top level GlassFish repository just to hold a single file copyright-exclude.Moreover removing it would simplify running the copyright checks on the GlassFish workspace remove the pre-requisite of building the copyright module.
We would split the configuration and maintain excludes in different parts of the workspace.
E.g:
    nucleus/pom.xml
    appserver/pom.xml
    appserver/tests/pom.xml
3.**Remove top level 'main' directory**:In time of GitHub migration, we split glassfish\~svn and created logical repositories. 'main' directory was there to separate GlassFish code from other code that used to reside under glassfish\~svn/trunk. Post GitHub migration, as we have separate repository for each of the sub projects, now GlassFish GitHub repository contains only GlassFish source code. As main becomes redundant now, I am planing to remove main.Post refactoring, the top level directories/files would be
    .github
    appserver
    nucleus
    .gitignore
    CONTRIBUTING.md
    LICENSE
    README.md
    pom.xml

### PR DESCRIPTION
**Pull request by arindam-bandyopadhyay**
Fix  #21822

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by bshannon — COMMENTED** [review]
I'm still looking at the details of the copyright module removal but I expected there to be more entries in the exclude list in the top level pom.xml.  It seems like nucleus/pom.xml is considered the "top level" configuration and the configuration in the actual top level pom.xml is only for the few files in the top level directory itself.  Is that the intent?  Why not put the common stuff in the real top level pom.xml?

Also, there seems to be some inconsistency in how the exclude entries in (e.g.) nucleus/pom.xml are handled.  Should they include the "nucleus" directory in the path?  Or should they just include the path below "nucleus"?

Shouldn't the copyright-vesion-plugin property be declared in the top level pom.xml (only)?  It's weird that it's declared and used in nucleus/pom.xml but the version number is written directly in the top level  pom.xml configuration.

**Review by yaminikb — DISMISSED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@bshannon 
nucleus/pom.xml is the 'parent' pom of all the GlassFish modules. The  "top level" pom.xml is not the 'parent' pom of any module. In order to exclude work (i.e parent pom.xml exclude list to propagate to child pom.xml) there needs to be parent child relationship between the pom.xml of the respective modules. So we need to define common excludes in nucleus/pom.xml not in "top level" pom.xml . 

Same is true for the copyright-vesion-plugin property be declared in the top level  nucleus/pom.xml (i.e there should be parent child relationship between pom.xml in order to 'property' to propagate from parent to child).

I have fixed some inconsistency in  exclude entries in nucleus/pom.xml, appserver/pom.xml and appsserver/tests/pom.xml

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by bshannon** [comment]
What would be the consequence of making the top level pom.xml be the parent pom of the nucleus module?  Wouldn't that be a more obvious relationship between these modules instead of having one sub-module be the parent of other sub-modules?

**Comment by romain-grecourt** [comment]
The top level pom is not the parent but only an aggregator pom.
I.e It is used to create a Maven reactor that includes both nucleus and appserver.

This design was at the time reflecting the fact that nucleus could be released separately.
If we think that this is not relevant anymore, then we can consider Bill's suggestion.

Regarding maven properties and dependency management, would you move that to the top level pom.xml as well ?
If so, we would have to be consistent and move the ones from appserver's pom.xml as well.

**Comment by arindam-bandyopadhyay** [comment]
@bshannon @romain-grecourt 
Can we merge this PR and raise a separate issue (and thus PR)for making the "top level" pom parent of appserver and nucleus (If at all we want to do that i.e if releasing nucleus separately is not anymore a valid requirement anymore). None of the PR can be merged until we merge this PR.

**Comment by bshannon** [comment]
Maybe restructuring the poms isn't worth it, but...

Clearly we have no plans to split the nucleus off as a separate project.  And while we don't have any plans to release it separately, there's nothing that prevents all the artifacts produced under the nucleus module from being used separately, right?

If you decide to restructure this, then moving everything that's common to both the nucleus and the app server into the top level pom would make sense.

And yes, I'm fine with considering this as a separate project.  The thing that brought this up is the way you restructured the copyright configuration, which required a duplicated configuration at the top level.

**Pull request merged**
