### PR TITLE
Update javax.transaction-api version in master pom.xml to 1.3 for Issue 22465

### LINKED ISSUE #22465: Use JTA 1.3 jar
Glassfish needs to be updated to use the new JTA 1.3 API jar file.

## Environment Details
* GlassFish Version (and build number):
* JDK version:
* OS:
* Database:

----------

## Problem Description
See above

## Steps to reproduce
See above

## Impact of Issue
See above

### PR DESCRIPTION
**Pull request by ghost**
Fixes #22465

### CODE REVIEW

**Comment by sdfelts** [comment]
@glassfishrobot Run CI tests please

**Comment by sdfelts** [comment]
@glassfishrobot Run CI tests please

**Comment by sdfelts** [comment]
@glassfishrobot Run CI tests please

**Review by russgold — APPROVED** [review]

**Review by bshannon — APPROVED** [review]

**Comment by sdfelts** [comment]
@glassfishrobot Run CI tests please

**Comment by yaminikb** [comment]
Server startup is failing with this update, hence all tests have failed:

Caused by: org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.resources.javamail-connector [43](R 43.0): missing requirement [org.glassfish.main.resources.javamail-connector [43](R 43.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.resource)(version>=1.7.0)(!(version>=2.0.0))) [caused by: Unable to resolve javax.resource-api [103](R 103.0): missing requirement [javax.resource-api [103](R 103.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.transaction)(version>=1.2.0)(!(version>=1.3.0)))] Unresolved requirements: [[org.glassfish.main.resources.javamail-connector [43](R 43.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.resource)(version>=1.7.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4148)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2118)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)

**Comment by yaminikb** [comment]
Discarding this PR since it has been taken care of  #22480

**Pull request closed without merging**
