### PR TITLE
Fix for #21738 - Number of Stateful session beans in Passive state is not updated (always 0) in Jconsole

### PR DESCRIPTION
**Pull request by srinivaskrishnan**
Fix for #21738 - Number of Stateful session beans in Passive state is not updated (always 0) in Jconsole

### CODE REVIEW

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by srinivaskrishnan** [comment]
Failure is in security tests some build failure not related to the code. So triggering once again the CI test for these changes

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by yaminikb** [comment]
Merged after confirming tests have passed.

**Pull request merged**
