### PR TITLE
Fixing ql_gf_web_profile_all test failure 

### PR DESCRIPTION
**Pull request by arindam-bandyopadhyay**
Fixing ql_gf_web_profile_all test failure

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run ci tests please

**Review by jigneshbhodia — APPROVED** [review]
looks good.

**Review by jigneshbhodia — APPROVED** [review]
looks good.

**Review by jigneshbhodia — APPROVED** [review]
Looks good

**Review by jigneshbhodia — APPROVED** [review]
Looks good

**Pull request merged**
