### PR TITLE
Enabling disabled test after adding the flag -Ddeployment.resource.va…

### PR DESCRIPTION
**Pull request by naman223**
Fixing #22145 - enabling tests

### CODE REVIEW

**Comment by naman223** [comment]
@glassfishrobot  Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Comment by naman223** [comment]
@glassfishrobot  Run CI tests please

**Comment by mskdeepak-oracle** [comment]
I think you should also be adding a delete-jvm-option in each of these tests at the end. Otherwise, the jvm option will switch off resource validation for other tests also.

**Comment by naman223** [comment]
It's added at the end of group so might not be an issue. But added enabling code now.

**Comment by naman223** [comment]
@glassfishrobot Run CI tests please

**Review by mskdeepak-oracle — APPROVED** [review]
Looks good!

**Pull request merged**
