### PR TITLE
Yasson updated to 1.0.2

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>

### CODE REVIEW

**Comment by Tomas-Kraus** [comment]
run ci tests please

**Comment by Tomas-Kraus** [comment]
@glassfishrobot run ci tests please

**Comment by lukasj** [comment]
@glassfishrobot run ci tests please

**Comment by Tomas-Kraus** [comment]
Do not merge e620964  changeset. I just want to see the tests results with artifact from staging repo.

**Comment by Tomas-Kraus** [comment]
@glassfishrobot run ci tests please

**Comment by Tomas-Kraus** [comment]
@glassfishrobot run ci tests please

**Review by romain-grecourt — CHANGES_REQUESTED** [review]
remove the staging repository before merging

**Comment by jansupol** [comment]
Yasson 1.0.2 needs JSON-P 1.1.2 to work properly. JSON-P 1.1.2 is to be merged by PR 22584.

**Comment by Tomas-Kraus** [comment]
ok, we can test this when PR 22584 is merged

**Comment by Tomas-Kraus** [comment]
@glassfishrobot run ci tests please

**Comment by jansupol** [comment]
JsonP is not properly updated. JSON-P has a separate commit #22587. Then we could create a new Yasson 1.0.2 merge, but only after Yasson is actually released

**Review by jansupol — CHANGES_REQUESTED** [review]
This PR should be closed in favor of a new one

**Pull request closed without merging**
