### PR TITLE
moving jaxr-ra code to GF code base.

### PR DESCRIPTION
**Pull request by ankathur**

### CODE REVIEW

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Review by yaminikb — CHANGES_REQUESTED** [review]

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Review by yaminikb — DISMISSED** [review]

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
