### PR TITLE
Fix #21566 BATCH CLI: NPE on asadmin list-batch-job-executions

### LINKED ISSUE #21566: BATCH CLI: NPE on asadmin list-batch-job-executions
When there is no job execution on the remote cluster, asadmin list-batch-job-executions shows:

```
>asadmin list-batch-job-executions --target cluster1
remote failure: java.lang.NullPointerException
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
An error occurred during replication
Failure: Command _ListBatchJobExecutions failed on server instance cluster_ins1: remote failure: No Job Executions found
Command list-batch-job-executions failed.
```

The above 'remote failure: java.lang.NullPointerException' doesn't say anything meaningful. Here is the statck trace :

```
[2016-09-26T10:34:51.746+0900] [glassfish 5.0] [SEVERE] [NCLS-CORE-00003] [javax.enterprise.system.core] [tid: _ThreadID=52 _ThreadName=admin-listener(2)] [timeMillis: 1474853691746] [levelValue: 1000] [[
  Exception while running a command
java.lang.NullPointerException
	at org.glassfish.batch.ListBatchJobExecutionsProxy.postInvoke(ListBatchJobExecutionsProxy.java:133)
	at org.glassfish.batch.AbstractListCommandProxy.execute(AbstractListCommandProxy.java:133)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
<snip>
```

the following 'subProperties' is null, but I'm not so sure it is intended or not.

```
**org.glassfish.batch.ListBatchJobExecutionsProxy.java:130**    protected void postInvoke(AdminCommandContext context, ActionReport subReport) {
        Properties subProperties = subReport.getExtraProperties();
        Properties extraProps = context.getActionReport().getExtraProperties();
NPE here----> if (subProperties.get("listBatchJobExecutions") != null)
            extraProps.put("listBatchJobExecutions", subProperties.get("listBatchJobExecutions"));
    }
```
#### Affected Versions
[4.1.1, 5.0]

### PR DESCRIPTION
**Pull request by srinivaskrishnan**
Fix #21566 BATCH CLI: NPE on asadmin list-batch-job-executions

### CODE REVIEW

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — CHANGES_REQUESTED** [review]
This still does not fix the issue. What tests did you do?

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
