### PR TITLE
Removing JMX/MP support

### PR DESCRIPTION
**Pull request by yaminikb**

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by bshannon — DISMISSED** [review]

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]
Looks good

**Pull request merged**
