### PR TITLE
Integrate Metro 2.4.2

### PR DESCRIPTION
**Pull request by lukasj**
and related components:
JAXB API - 2.3.1
JAXB RI - 2.3.1
Mimepull - 1.9.10
Stax2 API - 4.1
Woodstox - 5.1.0

### CODE REVIEW

**Comment by lukasj** [comment]
@glassfishrobot run ci tests please

**Comment by lukasj** [comment]
@glassfishrobot run ci tests please

**Comment by lukasj** [comment]
@glassfishrobot run ci tests please

**Comment by lukasj** [comment]
Each run shows different failures, time outs only

**Comment by jansupol** [comment]
Same failures as Jersey #22588 and Tyrus #22582.

**Comment by vinayvishal** [comment]
These failures are most likely due to some existing issue with CI pipeline. If changes are final, then we can go ahead and merge the PR. Can you please confirm?

**Comment by lukasj** [comment]
yes, this is ready for the merge

**Review by vinayvishal — APPROVED** [review]
Looks good to me.

**Comment by vinayvishal** [comment]
> yes, this is ready for the merge

I have merged the changes. These changes would also be required in eclipse-ee4j/glassfish. Can you please raise the PR for both master and EE4J_8 branch having these changes. Thanks!!

**Comment by lukasj** [comment]
done

**Pull request merged**
