### PR TITLE
Tests cleanup - round 1

### PR DESCRIPTION
**Pull request by yaminikb**
-Removed unwanted files
-Updated JUnit
-Added missing sources

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by bshannon — DISMISSED** [review]
Removing appserver/tests/appserv-tests/devtests/web/webappLoaderEmptyJar/lib/empty2.jar may defeat the purpose of the test.  You should probably leave it there.

Otherwise, as far as I can tell, these changes look fine, but I'm assuming you've verified that these tests continue to pass.  Ideally you would also verify that they fail when they're supposed to fail, but I understand that's much more difficult.

**Comment by yaminikb** [comment]
@bshannon  I thought one empty jar should suffice and hence removed the second. But you are right, the 2 empty jars in webappLoaderEmptyJar test must be there for a reason. They are bundled into the app. I've restored empty2.jar as suggested.

Yes, I have run the CI tests and verified they pass.

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by bshannon — APPROVED** [review]

**Pull request merged**
