### PR TITLE
Fix to validate http headers and redirect URLs

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Fix to validate http headers and redirect URLs

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by anissalam — DISMISSED** [review]
looks correct to me.

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
