### PR TITLE
Fixes #22165 : No tests are running for embedded_publisher_all test id

### LINKED ISSUE #22165: No tests are running for embedded_publisher_all test id
Currently, no tests are running for "embedded_publisher_all" test id. There were 48 tests that used to run for this test-id before migration. Need to fix this.

### PR DESCRIPTION
**Pull request by kokil12**
Fixes #22165.
The suggested modification runs all the 48 tests that used to be there before migration.

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI Tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI Tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI Tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI Tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
