### PR TITLE
Resources cleanup fixes in various modules

### PR DESCRIPTION
**Pull request by yaminikb**
-Auto close resources after use

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by jayasheelankumar — APPROVED** [review]

**Pull request merged**
