### PR TITLE
Fixes #22304 :  Remove console update-center plugin

### LINKED ISSUE #22304: Remove console update-center plugin
The Update Center option has been commented in console but the backend code and console plugin (console-updatecenter-plugin.jar) still exists.
Need to be removed.
Also, the online help pages related to update center need to be cleaned.

### PR DESCRIPTION
**Pull request by kokil12**
Fixes #22304 : 
The below modifications completely removes the update center backend code and all the dependency which uses the "console-updatecenter-plugin.jar".
Also, help pages related to update center have also been removed.

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by yaminikb** [comment]
@kokil Did you run GUI developer tests?

**Comment by kokil12** [comment]
Yes, have successfully ran the gui devtests today.

**Review by yaminikb — APPROVED** [review]

**Review by anissalam — APPROVED** [review]
Looks good to me.  thanks.

**Pull request merged**
