### PR TITLE
Using glassfish-copyright-maven-plugin 1.42 and Fixed copyright for all the files that was broken due to git migration

### PR DESCRIPTION
**Pull request by arindam-bandyopadhyay**
1.Using glassfish-copyright-maven-plugin 1.42
2.Fixed copyright for all the files that was broken due to git migration

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — DISMISSED** [review]
GitHub Desktop helps while reviewing such large file sets. I was able to go through all the changes.

It is surprising these copyright bugs were not caught earlier, looks like quite a few bugs are fixed in the latest plugin.

Apart from the simple year change in most files, bulk of the changes are in the appserv-tests files.

Hopefully, the plugin has done a thorough job in identifying all the files and repairing them and no more files are missed.

Just one question - Once these changes are in, will you be including the copyright job as well in the CI tests?

**Comment by arindam-bandyopadhyay** [comment]
Yes. Once the changes are in ,I would include copyright job  in Pull Request based CI pipeline and Continuous Check pipeline

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — DISMISSED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by bshannon — APPROVED** [review]

**Pull request merged**
