### PR TITLE
Fix #21797 Integrate Yasson to GlassFish

### LINKED ISSUE #21797: Integrate Yasson to GlassFish
Create an integration of Yasson to GlassFish

### PR DESCRIPTION
**Pull request by Verdent**
Fix for [#21797](https://github.com/javaee/glassfish/issues/21797)

### CODE REVIEW

**Comment by Verdent** [comment]
@glassfishrobot Run CI tests please

**Comment by romain-grecourt** [comment]
The IPS changes are not required (IPS support is dropped).
We may remove packages entirely, so lets avoid creating new packages.

Can you instead add those jsonb dependencies into the existing json package ?

**Comment by Verdent** [comment]
I guess that would be no problem, but just let me to confirm what I should do. I should remove that yasson packager and merge its dependencies to json packager which currently holds Json-p dependencies? Is that correct?

**Comment by romain-grecourt** [comment]
Yes, correct.

**Comment by Verdent** [comment]
I have made changes according to your suggestions.

**Comment by bravehorsie** [comment]
Updated versions to latest available in central, removed yasson eclipse repository.

**Comment by pavelbucek** [comment]
@glassfishrobot Run CI tests please

**Comment by pavelbucek** [comment]
@romain-grecourt @yaminikb can you please review this one?

**Review by romain-grecourt — APPROVED** [review]
OK, Yasson is now in maven central and the build passed.
LGTM

**Pull request merged**
