### PR TITLE
Change pwsd storage from String to char[]

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Change pwsd storage from String to char[]

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by JeffTancill — DISMISSED** [review]

**Comment by arjantijms** [comment]
One note for this PR; if it's done for security reasons, then one must realise it's not entirely certain that this actually helps.

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@arjantijms Thanks for the feedback, I agree merely making these changes will not address the issue completely since the problem is much deeper with lot of other dependent components. But this change will help in reduction of such issues in GlassFish code.

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
