### PR TITLE
issue 22270: correcting joda-time version, JSR sequence and adding ja…

### PR DESCRIPTION
**Pull request by ankathur**
…vax.money.

fixing part-2 of  #22270 user need to provide the joda jar in GF-HOME/modules/ folder.

### CODE REVIEW

**Comment by ankathur** [comment]
@glassfishrobot Run CI tests please

**Review by h2002044 — CHANGES_REQUESTED** [review]
Hibernate validator 6.0.1.Final uses the following OSGi package dependency
org.joda.time;version="[2.0.0,3.0.0)";resolution:=optional

Let us use the range 2.0.0, 3.0.0 instead of the range 1.6.0, 3.0.0

Other changes look fine.

**Comment by ankathur** [comment]
@glassfishrobot Run CI tests please

**Review by ankathur — COMMENTED** [review]
change submitted.

**Review by h2002044 — APPROVED** [review]

**Pull request merged**
