### PR TITLE
Fixes #22135. Move GlassFish man pages from glassfish-docs repository to glassfish repository.

### LINKED ISSUE #22135: Move GlassFish man pages from glassfish-docs repository to glassfish repository
Following are the objctives of this task :
1. Move contents of man/ under javaee/glassfish-docs repo to its desired location under glassfish repo.
2. Move contents of help/ under javaee/glassfish-docs repo to its desired location under glassfish repo.
3. Remove references of glassfish-docs dependencies in the relevant pom.xml files.
4. Run CI tests.

### PR DESCRIPTION
**Pull request by pranjal10**
Fixes #22135

### CODE REVIEW

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]

**Comment by pranjal10** [comment]
@glassfishrobot Run CI tests please

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
