### PR TITLE
Fix #22156: Bug in annotation handling in case of plural annotation handlers

### LINKED ISSUE #22156: EJB provider not passed in case of "plural" annotation handlers
Annotation handlers such as JMSDestinationDefinitionsHandler, JMSConnectionFactoryDefinitionsHandler invoke the processAnnotation function of their respective singular annotation handlers. The AnnotationTypesProvider - ejbProvider is not passed correctly during this process.

### PR DESCRIPTION
**Pull request by mskdeepak-oracle**
Fix #22156 - Using a plural annotation such as `AdministeredObjectDefinitionsHandler` would lead to a call to the `processAnnotation` function of its singular version `AdministeredObjectDefinitionHandler`. During this, the `ejbProvider` is not passed properly leading to a bug in the handling of these annotations.

I have added an additional constructor to facilitate this. Changed the code in all plural annotation handlers.

### CODE REVIEW

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Review by honghzzhang — COMMENTED** [review]
The changes look ok to me. Were there any tests failed due to this bug and passed with your change?

**Comment by mskdeepak-oracle** [comment]
No, this was just something I have observed while analysing the jms failure.

**Review by honghzzhang — APPROVED** [review]
In general, at this late point of development lifecycle, I would say only submit changes that are really necessary to maintain the stability of the code base. But the changes look  harmless enough so I will approve it.

**Pull request merged**
