### PR TITLE
Fixes #21896: Default group to role mapping.

### LINKED ISSUE #21896: Default group to role mapping.
## Environment Details
* GlassFish Version (and build number):5.0
----------

## Problem Description.
As per JSR 375.
>1.2.1. Group-To-Role Mapping
Various Java EE specifications define how roles are declared for an application, and how access to
application resources can be restricted to users that have a specific role. The specifications are
largely silent on the question of how users are assigned to roles, however. Most application servers
have proprietary mechanisms for determining the roles a user has.
Application servers MUST provide a default mapping from group names to roles. That is, a caller
who is a member of group "foo" is considered to have role "foo". This default mapping MAY be
overridden by proprietary configuration, but, when not overridden, provides sensible and
predictable behavior for portable applications.
An application MAY provide a default mapping from caller principal names to roles. That is, a caller
with the name "bar" is considered to have role "bar". This default mapping MAY be overridden by
proprietary configuration.

This is the issue to fulfil the above requirement.

### PR DESCRIPTION
**Pull request by sameer-pandit**
Fixes #21896: Default group to role mapping.

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
