### PR TITLE
Upgrade JavaMail to version 1.6.2.

### PR DESCRIPTION
**Pull request by bshannon**

### CODE REVIEW

**Comment by bshannon** [comment]
Issues seem to be disabled so I couldn't submit an issue to correspond to this.
This is the last JavaMail integration before contribution to Eclipse.

**Comment by bshannon** [comment]
@glassfishrobot Run CI tests please

**Comment by bshannon** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run ci tests please

**Comment by arindam-bandyopadhyay** [comment]
There are some intermittent failures. So the CI is failing. Merging this as the failures are unrelated to the change.

**Pull request merged**
