### PR TITLE
Fix for #21915: Error unregistering ProbeProvider

### PR DESCRIPTION
**Pull request by srinivaskrishnan**
Fix for #21915: Error unregistering ProbeProvider

### CODE REVIEW

**Comment by srinivaskrishnan** [comment]
Need to review the fix myself before adding the reviewer.

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Comment by srinivaskrishnan** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
