### PR TITLE
Split cts smoke tests to reduce runtime

### PR DESCRIPTION
**Pull request by debayan-gupta**

### CODE REVIEW

**Comment by debayan-gupta** [comment]
@glassfishrobot Run CI tests please

**Comment by debayan-gupta** [comment]
@glassfishrobot Run CI tests please

**Comment by debayan-gupta** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Comment by debayan-gupta** [comment]
@glassfishrobot Run CI tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]

**Pull request merged**
