### PR TITLE
Fixes #21983 : Escaped single quote with double single quote

### LINKED ISSUE #21983: Handle log messages in MessageFormat by escaping double single quote
## Environment Details
* GlassFish Version (and build number):
* JDK version:
* OS:
* Database:

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Fixes #21983 : The suggested fix is to escape single quote with double single quote while using MessageFormat.

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]
Looks good

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by yaminikb** [comment]
Merged after verifying that all tests passed except one copyright failure which is unrelated.

**Pull request merged**
