### PR TITLE
Added validation for Redirect URLs Cookies and Headers

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Added validation for Redirect URLs Cookies and Headers.

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by anissalam — DISMISSED** [review]
This looks fine to me.  But  this is change in the web-core code.  You may want to have a reviewer from that team to take a look.

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by yaminikb** [comment]
Merged after confirming that the one failing suite passed separately.

**Pull request merged**
