### PR TITLE
Integrate Mojarra 2.3.1 for Issue #21722

### PR DESCRIPTION
**Pull request by edburns**
- Upgrade to Mojarra 2.3.1 for Issue #21722 

	modified:   main/appserver/pom.xml

### CODE REVIEW

**Comment by edburns** [comment]
@glassfishrobot run ci tests please

**Comment by edburns** [comment]
@glassfishrobot run ci tests please

**Comment by edburns** [comment]
@glassfishrobot run ci tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run ci tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]

**Pull request merged**
