### PR TITLE
Hk2 v2.5.0-b62 integration to Glassfish

### PR DESCRIPTION
**Pull request by ankathur**

### CODE REVIEW

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Review by vinayvishal — APPROVED** [review]
Looks good.

**Pull request merged**
