### PR TITLE
Fixes #21930 : Resolves few Findbugs low priority issues

### LINKED ISSUE #21930: Resolve Findbugs low priority issues
## Environment Details
* GlassFish Version (and build number):
* JDK version:
* OS:
* Database:

----------

## Problem Description
Resolve Findbugs low priority issue

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Fixes #21930 : The suggested fix resolves some of the Findbugs low priority issues.

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
Starting CI tests run

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — DISMISSED** [review]
Looks good

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by yaminikb** [comment]
The test result message wan't reported, hence verified the results separately before merging the PR.

**Pull request merged**
