### PR TITLE
Integ: Derby 10.13.1.1

### PR DESCRIPTION
**Pull request by yaminikb**
Updating to new repackaged GAV org.glassfish.external:derby-distribution -> org.galssfish.external:derby

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by arindam-bandyopadhyay — DISMISSED** [review]
Looks good

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]
Looks good

**Pull request merged**
