### PR TITLE
Fixes #21851 : Fixed Thread pools edit and delete operations

### LINKED ISSUE #21851: A thread pool with a special character cannot be deleted.
## Environment Details
* GlassFish Version (and build number):Glassfish 5.0-b07
* JDK version:1.8.0_112
* OS:Windows 2012 R2

----------

## Problem Description
A thread pool with a special character (test; or test/) cannot be deleted. 

## Steps to reproduce
1. Navigate to Configurations > [config] > Thread Pools
2. Click "New..." and create a new thread pool, named "test/" or "test;"
=> After saving, the Thread Pools page shows the new thread pool in the table
3. Select the checkbox for the new thread pool
4. Click "Delete" and then "OK" in the popup dialogue to proceed
=> The new thread pool doesn't get deleted, and remains in the table.

## Fix
The thread pool name is not URL-encoded for the config DELETE endpoint used in RestApiHandlers.deleteConfigCascade.
Changed gf.deleteConfigCascade to encode the REST request URL in the same way as gf.deleteCascade.

````
diff --git "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\RestApiHandlers-23e8e06.001.java" "b/C:\\gf5\\glassfish\\main\\appserver\\admingui\\common\\src\\main\\java\\org\\glassfish\\admingui\\common\\handlers\\RestApiHandlers.java"
index a31ab05b87..8baa594695 100644
--- "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\RestApiHandlers-23e8e06.001.java"
+++ "b/C:\\gf5\\glassfish\\main\\appserver\\admingui\\common\\src\\main\\java\\org\\glassfish\\admingui\\common\\handlers\\RestApiHandlers.java"
@@ -329,7 +329,7 @@ public class RestApiHandlers {
 
             for ( Map oneRow : selectedRows) {
                 try{
-                    String endpoint = prefix + "/" + oneRow.get(id);
+                    String endpoint = prefix + "/" + URLEncoder.encode((String) oneRow.get(id), "UTF-8");
                     RestUtil.restRequest(endpoint, payload, "DELETE",null, false);
                 }catch (Exception ex){
                     GuiUtil.getLogger().severe(
````

### PR DESCRIPTION
**Pull request by sumauppa**
Fixes #21851 : Fixed delete operation and Thread pools edit page.

### CODE REVIEW

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
Ran Admin GUI dev tests and ran successfully.

**Review by yaminikb — APPROVED** [review]

**Comment by yaminikb** [comment]
Merging after confirming that the one single test failure in the pipeline tests was a known intermittent failure and unrelated to these changes.

**Pull request merged**
