### PR TITLE
Create a new test suite in CI pipeline for web services tests 

### LINKED ISSUE #22056: Create a new test suite in CI pipeline for webservices tests
The task is to create a script to make the new test suite run on hudson.

### PR DESCRIPTION
**Pull request by kokil12**
Fixes #22056 : Adding run_test.sh script and modifying total test count in resultCount.sh.

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests Please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests Please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests Please

**Review by yaminikb — DISMISSED** [review]

**Review by arindam-bandyopadhyay — CHANGES_REQUESTED** [review]
Please add the cleanup logic. Please refer https://github.com/javaee/glassfish/blob/master/appserver/tests/appserv-tests/devtests/admin/cli/run_test.sh#L72

**Comment by arindam-bandyopadhyay** [comment]
Please add the test id in appserver/tests/test_groups/gating

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests Please

**Review by arindam-bandyopadhyay — APPROVED** [review]

**Pull request merged**
