### PR TITLE
Updating copyright of nucleus/grizzly, nucleus/osgi-platforms, appserver/grizzly, appserver/web and changing copyright plugin version to 1.49

### PR DESCRIPTION
**Pull request by kokil12**

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
