### PR TITLE
Mojarra version downgrade

### PR DESCRIPTION
**Pull request by arindam-bandyopadhyay**

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run ci tests please

**Review by jigneshbhodia — APPROVED** [review]
Looks good. I would say  the change is about restoring it to the correct version of Mojarra for Oracle Glassfish 5.0.1 release as mentioned by Ruolin Li

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run ci tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run ci tests please

**Comment by arindam-bandyopadhyay** [comment]
Merging as the failures are known failure.

**Pull request merged**
