### PR TITLE
Change to new coordinates of codemodel

### PR DESCRIPTION
**Pull request by yaminikb**
GlassFish is using an old version of codemodel and need to be updated to use the new coordinates. Codemodel is now part of JAXB RI

### CODE REVIEW

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]
Looks good

**Pull request merged**
