### PR TITLE
update and enable pushQueryString

### PR DESCRIPTION
**Pull request by shingwaichan**

### CODE REVIEW

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by edburns — APPROVED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Pull request merged**
