### PR TITLE
Issue_21355 Race condition in ConnectionPool (connectors-runtime)

### LINKED ISSUE #21355: Race condition in ConnectionPool (connectors-runtime)
First of all, apologies if this is in the wrong place/does not contain enough info/is completely wrong/something else is wrong. This is my first attempted bug report so please be kind! 

I have been using glassfish in a highly concurrent environment (~250 request/second) and I am running into an issue where occasionally threads completely stop. After some investigation I believe the issue is caused by a combination of having a jdbc-connection-pool with max-wait-time-in-millis=0 and a bug in glassfish. I have been able to narrow down where the thread is stuck to line 432 in ConnectionPool by taking a jstack of the application:

jdbc-connection-pool settings:

```
<jdbc-connection-pool validation-table-name="dual" datasource-classname="oracle.jdbc.pool.OracleDataSource" res-type="javax.sql.DataSource" name="databaseName" is-connection-validation-required="true" max-wait-time-in-millis="0" fail-all-connections="true" validate-atmost-once-period-in-seconds="60">
```

Jstack extract:

```
"Thread-A" daemon prio=10 tid=0x00007f57d05d9000 nid=0x418b in Object.wait() [0x000000004cf82000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000069e44e0f8> (a java.lang.Object)
	at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:432)
	- locked <0x000000069e44e0f8> (a java.lang.Object)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:245)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:170)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:338)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:301)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:190)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:165)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:160)
	at com.sun.gjc.spi.base.DataSource.getConnection(DataSource.java:113)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:123)
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:330)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:293)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.reconnect(DatasourceAccessor.java:565)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.reconnect(DatabaseAccessor.java:1508)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.incrementCallCount(DatasourceAccessor.java:305)
	- locked <0x000000069e44db50> (a org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:579)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:535)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1717)
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:566)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:207)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:193)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:264)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelect(DatasourceCallQueryMechanism.java:246)
	at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:197)
	at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:152)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:844)
	at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:137)
	at org.eclipse.persistence.internal.sessions.AbstractSession.internalExecuteQuery(AbstractSession.java:2831)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1516)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1498)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1449)
	at org.eclipse.persistence.sequencing.QuerySequence.select(QuerySequence.java:309)
	at org.eclipse.persistence.sequencing.QuerySequence.updateAndSelectSequence(QuerySequence.java:254)
	at org.eclipse.persistence.sequencing.StandardSequence.getGeneratedVector(StandardSequence.java:71)
	at org.eclipse.persistence.sequencing.Sequence.getGeneratedVector(Sequence.java:257)
	at org.eclipse.persistence.internal.sequencing.SequencingManager$Preallocation_NoTransaction_State.getNextValue(SequencingManager.java:664)
	at org.eclipse.persistence.internal.sequencing.SequencingManager.getNextValue(SequencingManager.java:1067)
	at org.eclipse.persistence.internal.sequencing.ClientSessionSequencing.getNextValue(ClientSessionSequencing.java:70)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:349)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:308)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.assignSequenceNumber(UnitOfWorkImpl.java:465)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNotRegisteredNewObjectForPersist(UnitOfWorkImpl.java:4231)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.registerNotRegisteredNewObjectForPersist(RepeatableWriteUnitOfWork.java:513)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNewObjectForPersist(UnitOfWorkImpl.java:4176)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.persist(EntityManagerImpl.java:440)
	at com.sun.enterprise.container.common.impl.EntityManagerWrapper.persist(EntityManagerWrapper.java:269)
```

I believe the issue is caused by a race condition where:

*   Thread A adds a waitMonitor to the waitQueue (Line 425)
*   Thread-B removes waitMonitor from the waitQueue (Line 1224)
*   Thread-B gets the lock for waitMonitor (Line 1231)
*   Thread-B calls waitMonitor.notifyAll() (Line 1235)
*   Thread-B releases the lock on waitMonitor
*   Thread-A gets the lock for waitMonitor (Line 429)
*   Thread-A calls waitMonitor.wait() (Line 432)

All other threads in the application remain unaffected.

com.sun.enterprise.resource.pool.ConnectionPool extract 1:

```
423 if (!blocked) {
424     //add to wait-queue 425     Object waitMonitor = waitQueue.addToQueue();
426     if (poolLifeCycleListener != null) {
427         poolLifeCycleListener.connectionRequestQueued();
428     }
429     synchronized (waitMonitor) {
430         try {
431             logFine("Resource Pool: getting on wait queue");
432             waitMonitor.wait(remainingWaitTime);
433 
434         } catch (InterruptedException ex) {
435             //Could be system shutdown. 436             break;
437         }
438 
439         //try to remove in case that the monitor has timed 440         // out.  We dont expect the queue to grow to great numbers 441         // so the overhead for removing inexistant objects is low. 442         if (_logger.isLoggable(Level.FINE)) {
443             _logger.log(Level.FINE, "removing wait monitor from queue: " + waitMonitor);
444         }
445         if (waitQueue.removeFromQueue(waitMonitor)) {
446             if (poolLifeCycleListener != null) {
447 poolLifeCycleListener.connectionRequestDequeued();
448             }
449         }
450     }
```

com.sun.enterprise.resource.pool.ConnectionPool extract 2:

```
1219    protected void More ...notifyWaitingThreads() {
1220        // notify the first thread in the waitqueue 1221        Object waitMonitor = null;
1222        synchronized (waitQueue) {
1223            if (waitQueue.getQueueLength() > 0) {
1224waitMonitor = waitQueue.remove();
1225if(poolLifeCycleListener != null) {
1226    poolLifeCycleListener.connectionRequestDequeued();
1227}
1228            }
1229        }
1230        if (waitMonitor != null) {
1231            synchronized (waitMonitor) {
1232if (_logger.isLoggable(Level.FINE)) {
1233    _logger.log(Level.FINE, "Notifying wait monitor : " + waitMonitor.toString());
1234}
1235waitMonitor.notifyAll();
1236            }
1237        } else {
1238            logFine(" Wait monitor is null");
1239        }
1240    }
```

Unfortunately I cannot find a way to consistently reproduce the issue, however even if it is not the cause, the above still appears to be a possible race condition. I have also checked and the surrounding code appears to be unchanged in version 4.1\.
#### Environment
Debian GNU/Linux 5.0.9, Java 1.6.0_26
#### Affected Versions
[3.1.2.2]

### PR DESCRIPTION
**Pull request by h2002044**
Fixes #21355

### CODE REVIEW

**Comment by h2002044** [comment]
@glassfishrobot run CI tests please

**Comment by h2002044** [comment]
All tests pass with known failures
2 in security and 7 in servlet tck.

**Comment by h2002044** [comment]
@glassfishrobot run CI tests please

**Comment by h2002044** [comment]
@glassfishrobot run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
