### PR TITLE
Hk2 groupid change

### PR DESCRIPTION
**Pull request by ankathur**

### CODE REVIEW

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Review by romain-grecourt — APPROVED** [review]
looks good. Make sure you do a build without the glassfish gavs in your local repository.

You could do something like this: `rm -rf ~/.m2/repository/org/glassfish/main`

**Comment by ankathur** [comment]
@glassfishrobot run ci tests please

**Review by vinayvishal — COMMENTED** [review]
LGTM!

**Review by vinayvishal — APPROVED** [review]

**Pull request merged**
