### PR TITLE
Changing javaee-api module for JavaEE8

### LINKED ISSUE #22205: Change  javaee-api module for JavaEE8
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):
glassfish-5.0-b19
* JDK version:JDK8u144
* OS: ALL
* Database: NA

----------

## Problem Description
We need to fix  javaee-api module for JavaEE8. The following changes are needed
* Change all JavaEE7 reference to JavaEE8
*  Delete javaee endorsed API. As that's not an official JavaEE API
* Update the spec license 
* Update META-INF/LICENSE.txt from CDDL 1.0 to CDDL+GPL
* Remove jsr181-api, javax.xml.soap-api and jaxws-api
## Steps to reproduce
NA

## Impact of Issue
This is a must for JavaEE8 API generation and javadoc generation.

### PR DESCRIPTION
**Pull request by arindam-bandyopadhyay**
Fixes #22205

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI Tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI Tests please

**Review by yaminikb — DISMISSED** [review]
Seems fine

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI Tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI Tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI Tests please

**Review by bshannon — APPROVED** [review]
Looks good to me.

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
