### PR TITLE
Fix #21934: Add defaultContextPathEar in web test build.xml and not include in the run

### LINKED ISSUE #21934: Add defaultContextPathEar in web test build.xml and not include in the run
Add devtests/web/servlet-4.0/defaultContextPathEar in appserv-tests/devtests/web/build.xml.
And add it to exclude list until the test run.

### PR DESCRIPTION
**Pull request by shingwaichan**

### CODE REVIEW

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Review by edburns — DISMISSED** [review]

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]
Looks good to me

**Pull request merged**
