### PR TITLE
Updated JSON-P version

### PR DESCRIPTION
**Pull request by jansupol**
json-p has been split into api jar and impl jar in 1.1.2

Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
@glassfishrobot run ci tests please

**Comment by lukasj** [comment]
@glassfishrobot run ci tests please

**Comment by jansupol** [comment]
javax.json.JsonException: Provider org.glassfish.json.JsonProviderImpl not found

**Comment by jansupol** [comment]
Also java.security.AccessControlException: access denied ("javax.xml.ws.WebServicePermission" "CTSPermission3_name"). Is there the "doPrivilage" block removed in the JSON-P due to jdk 9 behaviour? Are more permission grants needed in the CTS tests?

**Comment by jansupol** [comment]
The CTS tests would need to be fixed, I assume. Since JSON-P jar has been split, CTS has just one jar on classpath (the RI now), and not the API. JSON-P 1.1 had just a single jar containing both RI and API. Not sure where the CTS for GF is taken from.

**Comment by jansupol** [comment]
@vinayvishal @arindam-bandyopadhyay any hint on where the GF CTS is?

**Comment by jansupol** [comment]
closing in favor of #22590

**Pull request closed without merging**
