### PR TITLE
Fix #21356: Validate resource adapter name specified as part of @CFD, @AODD annotations and through app-scoped resources

### LINKED ISSUE #21356: Validation : Ensure that valid resource-adapter name is specified in @ConnectionFactoryDefinition/@AdministeredObjectDefinition
As per the java-doc of @ConnectionFactoryDefinition.resourceAdapter(), the resource adapter specified must be available during deployment time:
[http://docs.oracle.com/javaee/7/api/javax/resource/ConnectionFactoryDefinition.html#resourceAdapter%28%29](http://docs.oracle.com/javaee/7/api/javax/resource/ConnectionFactoryDefinition.html#resourceAdapter%28%29)

It implicitly indicates that deployment of the application archive that has these annotations (@ConnectionFactoryDefinition, @AdministeredObjectDefinition") can be failed if the resource-adapter name is invalid.

Today, GlassFish does not fail deployment of the archive, instead during first time lookup of the resource, the lookup will fail. Need to fix this behavior and make sure that validation is done as part of application deployment.
#### Affected Versions
[4.1]

### PR DESCRIPTION
**Pull request by mskdeepak-oracle**
Fix #21356 

Add validation logic for resource-adapter names. Strategy for validation:
- Look in the domain.xml for stand alone RA's
- Look in the application's rar descriptors for embedded RA

Need to run connector_all devtests before merging.

### CODE REVIEW

**Comment by mskdeepak-oracle** [comment]
@h2002044, the validateRAName function has the core validation logic as we have discussed. Could you review the same?

**Review by h2002044 — DISMISSED** [review]

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Comment by mskdeepak-oracle** [comment]
The connector_all tests have passed :smile:

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
