### PR TITLE
Ant and Antlr upgrade

### LINKED ISSUE #22053: Update ant and antlr.
Update:
1. ant from 1.8.2 -> 1.10.1 
2. antlr from 2.7.6 - > 2.7.7 
3. maven-bundle-plugin for ant external package. 2.0.1 -> 3.3.0
Use ant repackaged for other modules.

### PR DESCRIPTION
**Pull request by sameer-pandit**
Fixes #22053.

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests Please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests Please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests Please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests Please

**Review by romain-grecourt — APPROVED** [review]
LGTM

**Pull request merged**
