### PR TITLE
fix #21707 : Dead lock between HttpSession#invalidate and HttpSession#getAttribute

### LINKED ISSUE #21707: Dead lock occurs when both HttpSession#invalidate() and HttpSession#getAttribute(String) are called at the same time.
Dead lock occurs when both HttpSession#invalidate() and HttpServletRequest#getAttribute(String) are called at the same time.

This is a reproducible application.

```
**TestServlet.java**package test.session.deadlock;

import java.io.IOException;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

@WebServlet(urlPatterns={"/test"})
public class TestServlet extends HttpServlet {
    static int counter = 0;

    public void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException {
        HttpSession session = req.getSession();

        boolean invalidate = Boolean.valueOf((String) req.getParameter("invalidate"));
        if(invalidate) {
            session.invalidate();
        }

        Integer id = null;
        synchronized(TestListener.lock) {
            id = (Integer)session.getAttribute("id");
        }

        if(id == null) {
            id = ++counter;
            session.setAttribute("id", counter);
            session.setMaxInactiveInterval(60);
        }

        res.getWriter().println("id="+id);
    }
}
```
```
**TestListener.java**package test.session.deadlock;

import javax.servlet.annotation.WebListener;
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionListener;

@WebListener
public class TestListener implements HttpSessionListener {
    static final Object lock = new Object(); 

    @Override
    public void sessionCreated(HttpSessionEvent event) {
    }

    @Override
    public void sessionDestroyed(HttpSessionEvent event) {
        synchronized(lock) {
            System.out.println("sessionDestroyed called");
        }
    }

}
```

Servlet calls HttpSession#getAttribute() in synchronized block.
In getAttribute method, session object is locked in order to check foreground session lock.

```
**StandardSession.java**    public boolean isForegroundLocked() {
        //in this case we are not using locks
        //so just return false
        if(_sessionLock == null)
            return false;        
        synchronized(this) {
            return _sessionLock.isForegroundLocked();
        } 
    }
```

Moreover, HttpSessionListener#sessionDestroyed() uses synchronized block.
HttpSessionListener#sessionDestroyed() is called after locking session object.

```
**StandardSession.java**    public void expire(boolean notify, boolean persistentRemove) {

        // Mark this session as "being expired" if needed
        if (expiring)
            return;

        synchronized (this) {

            if (manager == null)
return;

            expiring = true;

            // Notify interested application event listeners
            // FIXME - Assumes we call listeners in reverse order 
            // The call to expire() may not have been triggered by the webapp.
            // Make sure the webapp's class loader is set when calling the
            // listeners
            ClassLoader oldTccl = null;
            if (context.getLoader() != null &&
    context.getLoader().getClassLoader() != null) {
oldTccl = Thread.currentThread().getContextClassLoader();
if (Globals.IS_SECURITY_ENABLED) {
    PrivilegedAction<Void> pa = new PrivilegedSetTccl(
            context.getLoader().getClassLoader());
    AccessController.doPrivileged(pa);
} else {
    Thread.currentThread().setContextClassLoader(
            context.getLoader().getClassLoader());
}
            }
            try {
List<HttpSessionListener> listeners = context.getSessionListeners();
if (notify && !listeners.isEmpty()) {
    HttpSessionEvent event = new HttpSessionEvent(getSession());
    int len = listeners.size();
    for (int i = 0; i < len; i++) {
        // Invoke in reverse order of declaration
        HttpSessionListener listener = listeners.get((len - 1) - i);
        try {
            fireContainerEvent(context,
               "beforeSessionDestroyed",
               listener);
            listener.sessionDestroyed(event);
            fireContainerEvent(context,
               "afterSessionDestroyed",
               listener);
        } catch (Throwable t) {
            try {
fireContainerEvent(context,
   "afterSessionDestroyed",
   listener);
            } catch (Exception e) {
// Ignore
            }
            // FIXME - should we do anything besides log these?
            log(rb.getString(SESSION_EVENT_LISTENER_EXCEPTION), t);
        }
    }
}
            } finally {
if (oldTccl != null) {
    if (Globals.IS_SECURITY_ENABLED) {
        PrivilegedAction<Void> pa =
            new PrivilegedSetTccl(oldTccl);
        AccessController.doPrivileged(pa);
    } else {
        Thread.currentThread().setContextClassLoader(oldTccl);
    }
}
            }
```

This is the thread dump for dead lock.

```
Found one Java-level deadlock:
=============================
"ContainerBackgroundProcessor[StandardEngine[glassfish-web].StandardHost[server].StandardContext[/sessiondeadlock]]":
  waiting to lock monitor 0x000000005add7ee8 (object 0x00000000f6484960, a org.apache.catalina.session.StandardSession),
  which is held by "http-listener-1(8)"
"http-listener-1(8)":
  waiting to lock monitor 0x00000000527deb48 (object 0x00000000f60af8c8, a java.lang.Object),
  which is held by "http-listener-1(2)"
"http-listener-1(2)":
  waiting to lock monitor 0x000000005add7ee8 (object 0x00000000f6484960, a org.apache.catalina.session.StandardSession),
  which is held by "http-listener-1(8)"

Java stack information for the threads listed above:
===================================================
"http-listener-1(8)":
	at test.session.deadlock.TestListener.sessionDestroyed(TestListener.java:18)
	- waiting to lock <0x00000000f60af8c8> (a java.lang.Object)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:910)
	- locked <0x00000000f6484960> (a org.apache.catalina.session.StandardSession)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:854)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:842)
	at org.apache.catalina.session.StandardSession.invalidate(StandardSession.java:1603)
	at org.apache.catalina.session.StandardSessionFacade.invalidate(StandardSessionFacade.java:204)
	at test.session.deadlock.TestServlet.doGet(TestServlet.java:20)
"http-listener-1(2)":
	at org.apache.catalina.session.StandardSession.isForegroundLocked(StandardSession.java:1480)
	- waiting to lock <0x00000000f6484960> (a org.apache.catalina.session.StandardSession)
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:756)
	at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1354)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:152)
	at test.session.deadlock.TestServlet.doGet(TestServlet.java:25)
	- locked <0x00000000f60af8c8> (a java.lang.Object)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
```

Because the order of acquiring lock object is different between two threads,
dead lock occurs.

Moreover, the latest weld implementation (2.4.2 or 3.0.0) has the same structure.
So the same dead lock will occur if GF5.0 is released with the latest weld implementation.

When I replace weld of GF4.1.1(2.2.13) by newer version,
following dead lock occurs.

```
Daemon Thread [http-listener-1(40)] (Suspended)	
	owns: Collections$SynchronizedMap<K,V>  (id=180)	
		waited by: Daemon Thread [http-listener-1(7)] (Suspended)	
	waiting for: StandardSession  (id=179)	
		owned by: Daemon Thread [http-listener-1(7)] (Suspended)	
	StandardSession.isForegroundLocked() line: 1479	         *****lock of StandardSession
	StandardSession.isValid() line: 756	
	StandardSession.getAttribute(String) line: 1354	
	StandardSessionFacade.getAttribute(String) line: 152	
	EagerSessionBeanStore(AbstractSessionBeanStore).getAttribute(String) line: 88	
	EagerSessionBeanStore(AttributeBeanStore).attach() line: 98	
	LazyHttpConversationContextImpl(AbstractConversationContext<R,S>).destroyConversation(S, String) line: 403	
	LazyHttpConversationContextImpl(AbstractConversationContext<R,S>).cleanUpConversationMap() line: 322	             *****lock of Conversations Map of weld)
	LazyHttpConversationContextImpl(AbstractConversationContext<R,S>).deactivate() line: 306	
	LazyHttpConversationContextImpl.deactivate() line: 98	
	ConversationContextActivator.deactivateConversationContext(HttpServletRequest) line: 166	
	HttpContextLifecycle.requestDestroyed(HttpServletRequest) line: 276	
	WeldListener(WeldInitialListener).requestDestroyed(ServletRequestEvent) line: 150	
	WebModule(StandardContext).fireRequestDestroyedEvent(ServletRequest) line: 5294	
	StandardHostValve.postInvoke(Request, Response) line: 255	
Daemon Thread [http-listener-1(7)] (Suspended)	
	owns: StandardSession  (id=179)	
		waited by: Daemon Thread [http-listener-1(40)] (Suspended)	
		waited by: Daemon Thread [http-listener-1(33)] (Running)	
		waited by: Daemon Thread [http-listener-1(31)] (Running)	
		waited by: Daemon Thread [http-listener-1(18)] (Running)	
		waited by: Daemon Thread [ContainerBackgroundProcessor[StandardEngine[glassfish-web].StandardHost[server].StandardContext[/apl]]] (Suspended)	
		waited by: Daemon Thread [http-listener-1(10)] (Running)	
		waited by: Daemon Thread [http-listener-1(9)] (Running)	
		waited by: Daemon Thread [http-listener-1(1)] (Running)	
	waiting for: Collections$SynchronizedMap<K,V>  (id=180)	
		owned by: Daemon Thread [http-listener-1(40)] (Suspended)	
	LazyHttpConversationContextImpl(AbstractConversationContext<R,S>).destroy(S) line: 366	          *****lock of Conversations Map of weld
	LazyHttpConversationContextImpl.destroy(HttpSession) line: 116	
	HttpSessionContextImpl.destroy(HttpSession) line: 63	
	HttpContextLifecycle.sessionDestroyed(HttpSession) line: 154	
	WeldListener(WeldInitialListener).sessionDestroyed(HttpSessionEvent) line: 144	
	StandardSession.expire(boolean, boolean) line: 910	*****lock of StandardSession
	StandardSession.expire(boolean) line: 854	
	StandardSession.expire() line: 842	
	StandardSession.invalidate() line: 1603	
	StandardSessionFacade.invalidate() line: 204	
	CDIServlet.doGet(HttpServletRequest, HttpServletResponse) line: 59
```
#### Affected Versions
[3.1.2.2, 4.1, 4.1.1, 5.0]

### PR DESCRIPTION
**Pull request by shingwaichan**

### CODE REVIEW

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by ghost — COMMENTED** [review]
How will this behave if this instance is serialized/deserialized?

**Comment by shingwaichan** [comment]
In PersistentManagerBase#processMaxActiveSwaps(), we have the following steps:
a) session.lockBackground()
b) swap out the session (serialized)
c) session.unlockBackground()

Before the proposed change, a), c) share the same lock as session.expire() and b) and session.expire() can run in parallel.
With the proposed change, a), b) and c) can be in parallel with session.expire().
When the session is swap in, it will be checked whether it is expired or not.
So, the semantic for expire and serialized/deserialized is essentially the same.

**Review by ghost — APPROVED** [review]

**Comment by arindam-bandyopadhyay** [comment]
Fix #21707

**Pull request merged**
