### PR TITLE
Integrate fix for getServletName return null, #21846

### PR DESCRIPTION
**Pull request by edburns**
Shing-wai, can you please review this, but don't officially approve it.  I want to get this pre-reviewed so that when the fix for https://github.com/javaee/grizzly/issues/1954 is integrated it can go right in.

Thanks,

Ed

### CODE REVIEW

**Comment by edburns** [comment]
Only the following commits need to be reviewed:

commit fb6850e24cb39d35e4db39f06138d677773864ad
Author: Ed Burns <edward.burns@oracle.com>
Date:   Fri Jun 23 18:54:02 2017 -0400

    Modify test to take fix for Grizzly #1950 into account

commit dfa43684c499de5379538728008a0a3335dbdbc5
Author: Ed Burns <edward.burns@oracle.com>
Date:   Fri Jun 23 18:12:23 2017 -0400

    WIP Test Grizzly fix for Servlet Name, Grizzly issue #1950.

commit 7cfc0836cb5cb9899d9e2ab6d96790552c7690fc
Author: Ed Burns <edward.burns@oracle.com>
Date:   Wed Jun 14 17:17:33 2017 -0400

    WIP experimental resolution

**Review by shingwaichan — COMMENTED** [review]
I notice that 2.4.0-beta10-SNAPSHOT is used in nucleus/pom.xml. SNAPSHOT should not be used here.

**Review by shingwaichan — COMMENTED** [review]
Per discussion with Ed, NAMED_DISPATCH_SERVLET_MAPPING is only used as a boolean. There is no need to have NamedDispatchHttpServletMapping, where all the methods return null. In this case, we would to add a ApplicationDispatcher constructor with additional boolean.

**Comment by edburns** [comment]
@shingwaichan Can you please review 99353197b595f8eaae9fefc65fd2a3688a966ea9 ?

**Comment by shingwaichan** [comment]
The new ApplicationDispatcher constructor has a different second argument in the second argument. In general, we will put the different argument at the end. You can just add a constructor with additional boolean argument in this case.

**Comment by shingwaichan** [comment]
The implementation of the constructor are almost the same. You can simplify this as  this(wrapper, ...., false) for the one with one argument less.

**Comment by shingwaichan** [comment]
The boolean argument is to check whether it is a named dispatcher. In this case, can we just check the "name" argument is null or not? Then we only need one constructor and change the code check (name != null).

**Comment by edburns** [comment]
@shingwaichan I think this is ready for review.
But I still need to get #22040 in before I request this to be merged.

**Comment by edburns** [comment]
@glassfishrobot run CI tests please

**Review by shingwaichan — APPROVED** [review]
The changes are good now.

**Pull request merged**
