### PR TITLE
Fixes #21898 : Added encoded config names

### LINKED ISSUE #21898: Add encoded names for config names.
Add encoded names for config names section.

### PR DESCRIPTION
**Pull request by sumauppa**
Fixes #21898 : Added encoded config names.

### CODE REVIEW

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Pull request merged**
