### PR TITLE
integrate hk2 2.5.0-b44

### PR DESCRIPTION
**Pull request by romain-grecourt**
The BV fixes Mason put into the config-generator (JSR-269 fixes) 
Some internal bug (13445398)

### CODE REVIEW

**Comment by romain-grecourt** [comment]
@glassfishrobot Run CI tests please

**Review by jwells131313 — APPROVED** [review]
+1

**Comment by romain-grecourt** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Comment by yaminikb** [comment]
Merged after verifying that all tests have passed except the servlet tck suite failure which is a known issue.

**Pull request merged**
