### PR TITLE
Fixes #22096 : Create a new test suite in CI pipeline for naming tests

### LINKED ISSUE #22096: Create a new test suite in CI pipeline for naming tests
The task is to create a script and make necessary changes in the test code so that this test suite can be added in CI pipeline.

### PR DESCRIPTION
**Pull request by kokil12**
Fixes #22096 : Adding run_test.sh script and creating necessary files to make this new test suite run.

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests Please

**Review by arindam-bandyopadhyay — CHANGES_REQUESTED** [review]
Please add the test id in appserver/tests/test_groups/gating

**Comment by kokil12** [comment]
Added the test-id in appserver/tests/test_groups/gating

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests Please

**Review by arindam-bandyopadhyay — DISMISSED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests Please

**Review by arindam-bandyopadhyay — APPROVED** [review]

**Pull request merged**
