### PR TITLE
Fixes  #22157 : Disable autocomplete in console pages.

### LINKED ISSUE #22157: Disable autocomplete in console pages.
Disable form autocomplete in console pages.

### PR DESCRIPTION
**Pull request by sumauppa**
Fixes  #22157 : Disable autocomplete in console pages.
Ran quicklook and console dev tests.

Console dev tests summary:
************************************
Tests run: 115, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 h
[INFO] Finished at: 2017-08-02T00:18:38-07:00
[INFO] Final Memory: 39M/211M

### CODE REVIEW

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Review by anissalam — DISMISSED** [review]

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot Run CI tests please

**Comment by sumauppa** [comment]
@glassfishrobot run ci tests please

**Comment by sumauppa** [comment]
Results :

Tests run: 116, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:15 h
[INFO] Finished at: 2017-08-07T00:08:02-07:00
[INFO] Final Memory: 40M/213M
[INFO] --------------------------

**Review by anissalam — APPROVED** [review]
Approve this, but please update the bug report with some info about the fix.  Why is the need of adding the 'name' field, so others can understand the change.

**Pull request merged**
