### PR TITLE
Fix #21198: Versioned applications cannot be enabled on individual cluster instances

### LINKED ISSUE #21198: Clustered / Versioned applications cannot be enabled on individual cluster instances
When deploying versioned applications, and trying to upgrade versions
instance-at-a-time, when enabling the first instance, all instances are disabled instead.

(version 1.0 working on the cluster)
$ asadmin deploy --enabled=false --target cluster app:1.1
(good)
$ asadmin enable --target inst1 app:1.1
(all versions of app are now inaccessible on all instance in the cluster)
i.e. Page Not Found error
#### Environment
aLL
#### Affected Versions
[4.1]

### PR DESCRIPTION
**Pull request by mskdeepak-oracle**
Fix #21198: In case of a rolling update, while enabling the new versioned application on first instance, we need to disable the current version of the application only this instance followed by enabling the new version on this instance.

There is a bug while the disabling happens. Fixed by allowing disable command to run only on the correct target

### CODE REVIEW

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Review by honghzzhang — DISMISSED** [review]
Changes look good.

**Comment by yaminikb** [comment]
@glassfishrobot run ci tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot run ci tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Comment by mskdeepak-oracle** [comment]
@glassfishrobot Run CI Tests please

**Pull request closed without merging**
