### PR TITLE
Remove redundant dependencies

### PR DESCRIPTION
**Pull request by vinayvishal**
Removes redundant RelaxNG dependencies

### CODE REVIEW

**Comment by vinayvishal** [comment]
@glassfishrobot Run CI tests please

**Comment by vinayvishal** [comment]
@glassfishrobot Run CI tests please

**Review by arindam-bandyopadhyay — APPROVED** [review]
Looks Good

**Comment by vinayvishal** [comment]
@glassfishrobot Run CI tests please

**Pull request merged**
