### PR TITLE
Split web tests to reduce the execution time

### PR DESCRIPTION
**Pull request by debayan-gupta**

### CODE REVIEW

**Comment by debayan-gupta** [comment]
@glassfishrobot Run CI tests please

**Review by shingwaichan — CHANGES_REQUESTED** [review]
build.xml
1. The indent of some antcall is not aligned.
2. There are a lot of wrapper target, e.g. web_jsp. I don’t think we need that.
3. The tests in servlet and web-container are duplicated in two different places. This is hard to maintain.
4. The servlet and web-container target takes about 24 and 23 min. Why do we break in into 13 and 8 parts? What is the requirement for the runtime of each part?
5. In my opinion, we don’t need to change the build.xml for this. We only need to change the run_test.sh

**Comment by debayan-gupta** [comment]
1.Corrected indentation.
2. There is a convention of appending the main module and then sub module, so that identification is  easier. Please let me know if you are not ok with this, I'll discuss this with build team. Another use is to have the 'finish-report' ant call to be part of each target as they will run as individual jobs.
3.Agree. But the provision to run all tests or target all should be supported. Hence kept the existing targets. If it is fine to remove the single target like servlet,web-container completely, it could be done and all target section could be modified.
4.The idea is to run each target as separate jenkins job which will run under a docker container. No specific runtime requirement but as minimal as possible hence we have enough resource to run parallel tests. Also in future with addition of more tests in the servlet and web-container, run time will increase.Here user could run a specific group of tests in less than 10 minutes.

**Comment by shingwaichan** [comment]
(1) is resolved. (2) is partial resolved. (3) is not resolved.
For (4), even if we want to run the tests into 10 min, I still do not see a need to break down servlet into 13 parts and web-container tests in 8 parts.

**Comment by debayan-gupta** [comment]
Grouping of servlet and web-container target removed as per the comment.
Wrapper target for servlet and web-container is required to run each of them as individual job and generate report.

**Comment by shingwaichan** [comment]
The wrapper targets are not necessary. In fact, it is less flexible and more difficult to maintenance. A more flexible logic can be accomplished in the run_test.sh. For instance, suppose you want to have a target called web_all_1 which run servlet. This can achieved in run_test.sh by:
* in get_test_target, add a case 'web_all_1' to set TARGET="init servlet finish-report"
This is more flexible as we can add other targets to the web_all_1 by changing the above TARGET.
Also, we can add web_all_2 by only changing run_test.sh.
Note that "-t" option in test_run is not used in run_test.sh. If you want to update the logic for this, then you need to update is_target for a list of arguments, etc.

**Comment by debayan-gupta** [comment]
Removed the wrapper targets and processing test id inputs to convert them into the actual build.xml targets.

**Comment by debayan-gupta** [comment]
Removed the wrapper targets and processing test id inputs to convert them into the actual build.xml targets.

**Comment by shingwaichan** [comment]
1. The existing codes in run_test.sh use tap rather than four spaces as indent. It would be good to keep the same conventions. 
2. There are many small targets, like web_ha, which only runs in less than 2 min in my farm machine. It this case it should compose with other targets to in the test run. (See web_all_1, web_all_2, etc in my previous comments. In this case, the gftest.sh only pass web_all_1 rather than a list of targets.)
3. "init" is missing (in addition to finish-report) is needed for other targets.

**Comment by shingwaichan** [comment]
I have looked at the diff of build.xml. I saw the following unnecessary extra whitespace added above the lines of 
        <target name=“el”
	<target name=“servlet”
	<target  name=“comet”
And there is additional unnecessary extra blank line added before
	<target name=“weblogicDD”

In run_test.sh, get_test_target(), please use “tab” rather than 4 spaces to align the method body in order to be consistent with the original codes.

**Comment by debayan-gupta** [comment]
Incorporated review comments related to new line and tabs.

**Review by shingwaichan — APPROVED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Pull request merged**
