### PR TITLE
Fixes #21307 Secure Client-Initiated Renegotiation cannot be disabled

### LINKED ISSUE #21307: Secure Client-Initiated Renegotiation cannot be disabled: DoS Danger
Glassfish 4.1 supports Secure Client-Initiated Renegotiation. However, this opens all doors for DoS attacks, see [https://community.qualys.com/blogs/securitylabs/2011/10/31/tls-renegotiation-and-denial-of-service-attacks](https://community.qualys.com/blogs/securitylabs/2011/10/31/tls-renegotiation-and-denial-of-service-attacks)

As Ivan Ristić found out there was an undocumented ability to disable client-initiated renegotiation in Java 8 (see [http://blog.ivanristic.com/2014/03/ssl-tls-improvements-in-java-8.html](http://blog.ivanristic.com/2014/03/ssl-tls-improvements-in-java-8.html)). However, this seems not to work at all (I guess it has been removed + it is undocumented anyway)! In other words: adding the following to <jdk1.8-HOME>/jre/lib/security/java.security does not help at all (whereas I think OpenJDK has support for this, but I did not crosscheck this):

jdk.tls.rejectClientInitiatedRenegotiation=true
jdk.tls.rejectClientInitiatedRenego=true

I have not found anything that allows to disable Secure Client-Initiated Renegotiation in the Glassfish settings. Since there seems to be no way to
disable it globally via JSSE (<jdk1.8-HOME>/jre/lib/security/java.security) I believe that Glassfish should introduce a way to disable it somehow. I believe this is very critical.
#### Environment
Ubuntu 14.04 LTS Server x64, java 1.8.0_31 + JCE Unlimited Strength, GlassFish Server Open Source Edition 4.1 (build 13)
#### Affected Versions
[4.1]

### PR DESCRIPTION
**Pull request by mukumawa**
Fixes #21307

### CODE REVIEW

**Comment by mukumawa** [comment]
@glassfishrobot Run CI tests please

**Comment by mukumawa** [comment]
@glassfishrobot Run CI tests please

**Comment by mukumawa** [comment]
@glassfishrobot Run CI tests please

**Review by JeffTancill — APPROVED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Pull request merged**
