### PR TITLE
Change permissions of artifacts in distributions.

### PR DESCRIPTION
**Pull request by sameer-pandit**

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
