### PR TITLE
Added validation for redirect URL to remove extra whitespaces

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Added validation for redirect URL to remove extra whitespaces.

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by edburns — COMMENTED** [review]
I will allow @shingwaichan to give the final approval.  Code-wise, this looks correct, but I'm concerned about the performance impact if this is invoked on every request.  Is it?

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
