### PR TITLE
First cut: Bean Validation 2.0 Integration

### PR DESCRIPTION
**Pull request by h2002044**
Draft changes for Bean Validation 2.0.0.Beta2 integration. Not for review.

### CODE REVIEW

**Review by yaminikb — DISMISSED** [review]
Changes seem fine

**Comment by gunnarmorling** [comment]
Hi, we've released CR 2 of the BV 2.0 spec and the RI Hibernate Validator 6 yesterday:

* http://beanvalidation.org/news/2017/07/05/bean-validation-2-0-cr2-is-out/
* http://in.relation.to/2017/07/05/hibernate-validator-600-cr2-out/

I'd recommend to integrate CR 2 right away, I don't expect any significant changes required when it comes to integrating these bits.

**Comment by gunnarmorling** [comment]
We've released versions 2.0.0.CR3 of the API and TCK and 6.0.0.CR3 of the RI, which are the versions we've submitted for the Final Approval Ballot. Note that we've made an improvement to the way how the RI bootstraps the EL expression factory in that release, so it should not be required any longer to re-package HV and add the OSGi imports for the com.sun.* EL classes.

**Comment by h2002044** [comment]
Closing this as another PR was raised to handle this requirement.
PR details:
https://github.com/javaee/glassfish/commit/60a673e03ac9602e83c2161f81d3be7d7e6f8935

**Pull request closed without merging**
