### PR TITLE
SessionContext.getCallerPrincipal() returns previous principal on TimerService.

### LINKED ISSUE #21667: SessionContext.getCallerPrincipal() returns previous principal on TimerService
1\. Authenticated users (for example USER1) call SSB asynchronous method with ejb-thread-pool1.

2\. TimerService's timeout method called with same ejb-thread-pool1, then SessionContext.getCallerPrincipal() returns USER1.

Example :

```
@Stateless
public class FooServiceImpl implements FooService {
    @Resource
    private SessionContext context;

    @Override
    @Asynchronous
    public void exec() {
        logger.info("exec()[{}]", context.getCallerPrincipal());
        // ...
    }
}
```

USER1 calls exec() then

> [__ejb-thread-pool1] INFO FooServiceImpl - exec()[USER1]

So TimerService is

```
@Singleton
@Startup
@ConcurrencyManagement(ConcurrencyManagementType.CONTAINER)
public class SchedulerService {

    @Resource
    private TimerService timerService;

    @Resource
    private SessionContext context;

    @PostConstruct
    public void postConstruct() {
        TimerConfig timerConfig = new TimerConfig();
        // ...
        timerService.createIntervalTimer(0, 10000, timerConfig);
    }

    @Timeout
    public void handleTimeout(Timer timer) {
        logger.info("handleTimeout()[{}]", context.getCallerPrincipal());
        // ...
    }
}
```

Log is

> [__ejb-thread-poolX] INFO SchedulerService - handleTimeout()[ANONYMOUS]
> [__ejb-thread-pool1] INFO SchedulerService - handleTimeout()[USER1]
> [__ejb-thread-poolX] INFO SchedulerService - handleTimeout()[ANONYMOUS]

ejb-thread-pool1 use previous principal !
#### Affected Versions
[3.1.2]

### PR DESCRIPTION
**Pull request by sameer-pandit**
Fixes #21667 . Reset the SecurityContext after the async call of EJB method.

### CODE REVIEW

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI tests please.

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Comment by sameer-pandit** [comment]
@glassfishrobot Run CI Tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
