### PR TITLE
Fixes #21819 : Updated maven-bundle-plugin version to 2.4.0

### LINKED ISSUE #21819: Upgrade maven-bundle-plugin to 2.4.0 to avoid bundle build issues with JDK8 lambda expressions.
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 5.0 latest
* JDK version: 1.8.0_131
* OS: any
* Database: N/A

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

Please see:  https://issues.apache.org/jira/browse/FELIX-4005

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

Unable to use lambda expressions within Grizzly or elsewhere within the GF code base due to
the error referenced in the apache issue above.

[//]: # "Please choose one each Type, Component, and Priority label"

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Fixes #21819 : The suggested fix is to update the maven-bundle-plugin version to 2.4.0 to avoid bundle build issues

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
@glassfishrobot Run CI tests please

**Comment by arindam-bandyopadhyay** [comment]
@jayasheelankumar 
Can we try to update the plugin to the latest version ? We are updating it to 2.4.0 however the latest is 3.3.0. Can we give a try to check if GlassFish works with 3.3.0

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Comment by yaminikb** [comment]
Closing this PR since its an incomplete change.

**Pull request closed without merging**
