### PR TITLE
integrate javax.servlet-api 4.0.0-b06

### PR DESCRIPTION
**Pull request by shingwaichan**

### CODE REVIEW

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Review by edburns — DISMISSED** [review]

**Comment by shingwaichan** [comment]
Starting CI tests run

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Review by edburns — DISMISSED** [review]

**Comment by arindam-bandyopadhyay** [comment]
@glassfishrobot Run CI tests please

**Review by edburns — APPROVED** [review]

**Comment by shingwaichan** [comment]
@glassfishrobot Run CI tests please

**Pull request merged**
