### PR TITLE
Updating copyright of jbi and osgi-javaee module

### PR DESCRIPTION
**Pull request by kokil12**

### CODE REVIEW

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by yaminikb** [comment]
@kokil12 Can you please remove all jbi tests as mentioned in #22113?

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — CHANGES_REQUESTED** [review]
It looks like the build files still have references to jbi targets. They can be removed as well.

**Comment by kokil12** [comment]
There was only one build.xml which referenced to jbi target. Have removed that reference.

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Comment by kokil12** [comment]
@glassfishrobot Run CI tests please

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
