### PR TITLE
Fixes #21981 : Fixed intermittent failures in admin GUI dev tests

### LINKED ISSUE #21981: Fix intermittent failures in admin GUI dev tests
Few tests were commented out due to intermittent failures in GUI dev tests.

### PR DESCRIPTION
**Pull request by sumauppa**
Fixes #21981 : Uncommented intermittent failures in admin GUI dev tests and fixed those.
Changed from localhost to hostname in base URL.
send AS_ADMIN_PASSWORDFILE as an argument to pass the password instead of hardcoding in secureadmin mode.

### CODE REVIEW

**Comment by sumauppa** [comment]
command to run tests:
**************************
mvn -DsecureAdmin=true -DAS_ADMIN_PASSWORDFILE=/tmp/password.txt test | tee results.log

Tests Result : 
****************
Tests run: 114, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 h
[INFO] Finished at: 2017-07-04T05:55:19-07:00
[INFO] Final Memory: 39M/206M
[INFO] ------------------------------------------------------------------------

**Comment by sumauppa** [comment]
@glassfishrobot run CI tests please

**Comment by sumauppa** [comment]
after changes, GUI results
Tests run: 115, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 h
[INFO] Finished at: 2017-07-05T23:46:14-07:00
[INFO] Final Memory: 39M/210M

**Comment by sumauppa** [comment]
@glassfishrobot run CI tests please

**Comment by sumauppa** [comment]
1)Uncommented out all the testcases, which were commented before due to intermittent failures and made few fixes to make it work.
2)In devtests, changed hostname from localhost to the actual host name.
3)In devtests, login password was hardcoded and made it in a way to put it in a file and pass that file name as an argument.
To run the secure tests,
mvn -DsecureAdmin=true -Dpasswordfile=<<location>> test | tee results.log

**Comment by sumauppa** [comment]
No more changes.  Please review and merge the changes.

**Review by yaminikb — APPROVED** [review]

**Pull request merged**
